# Generated by Django 2.2.3 on 2019-07-31 03:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tastes',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.IntegerField()),
                ('voted_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 3, 57, 29, 747015, tzinfo=utc))),
                ('current_value', models.IntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taste.Table')),
                ('taste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taste.Taste')),
            ],
        ),
    ]
