# Generated by Django 2.2.3 on 2019-07-31 04:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 31, 4, 28, 22, 30875, tzinfo=utc)),
        ),
    ]
